# Generated by Django 4.1.13 on 2024-06-16 08:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_clientuser_expiration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.CreateModel(
            name='CustomerRemain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusted_remain', models.IntegerField()),
                ('blocked_remain', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('current_remain', models.IntegerField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerageTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index', models.CharField(max_length=150)),
                ('AddedValueTax', models.IntegerField()),
                ('BondDividend', models.IntegerField()),
                ('BranchID', models.IntegerField()),
                ('BranchTitle', models.CharField(max_length=150)),
                ('Discount', models.IntegerField()),
                ('InstrumentCategory', models.BooleanField()),
                ('MarketInstrumentISIN', models.CharField(max_length=150)),
                ('NetPrice', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('TotalCommission', models.IntegerField()),
                ('TradeCode', models.IntegerField()),
                ('TradeDate', models.DateTimeField()),
                ('TradeItemBroker', models.IntegerField()),
                ('TradeItemRayanBourse', models.IntegerField()),
                ('TradeNumber', models.IntegerField()),
                ('TradeStationType', models.BooleanField()),
                ('TradeSymbol', models.CharField(max_length=200)),
                ('TradeType', models.CharField(max_length=150)),
                ('TransferTax', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('DateInt', models.IntegerField()),
                ('Update', models.DateTimeField(default=datetime.datetime(2024, 6, 16, 8, 40, 5, 418927, tzinfo=datetime.timezone.utc))),
                ('Name', models.CharField(max_length=200)),
                ('Fund', models.BooleanField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
