# Generated by Django 4.1.13 on 2024-06-20 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_brokeragetransactions_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokeragetransactions',
            name='Update',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 8, 5, 22, 523516, tzinfo=datetime.timezone.utc)),
        ),
    ]
