# Generated by Django 4.1.13 on 2024-05-21 07:33

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=11, unique=True)),
                ('is_person', models.BooleanField(default=True)),
                ('issue', models.CharField(blank=True, max_length=75, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DateTimeField(default=datetime.datetime(2024, 11, 17, 7, 33, 43, 185202, tzinfo=datetime.timezone.utc))),
                ('mobile', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='شماره همراه صحیح نیست')])),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='شماره ثابت صحیح نیست')])),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن'), ('U', 'نامشخص'), ('C', 'حقوقی')], default='U', max_length=1)),
                ('date_last_act', models.DateTimeField(default=django.utils.timezone.now)),
                ('card_number_bank', models.CharField(blank=True, max_length=16, null=True)),
                ('shaba_bank', models.CharField(blank=True, max_length=26, null=True)),
                ('marital', models.BooleanField(default=False)),
            ],
        ),
    ]
